export const FETCH_HEROES_BEGIN = 'FETCH_HEROES_BEGIN';
export const FETCH_HEROES_SUCCESS = 'FETCH_HEROES_SUCCESS';
export const FETCH_HEROES_FAILURE = 'FETCH_HEROES_FAILURE';
export const FETCH_HERO_BY_ID_BEGIN = 'FETCH_HERO_BY_ID_BEGIN';
export const FETCH_HERO_BY_ID_SUCCESS = 'FETCH_HERO_BY_ID_SUCCESS';
export const FETCH_HERO_BY_ID_FAILURE = 'FETCH_HERO_BY_ID_FAILURE';